ipam:
  mode: "cluster-pool"
  operator:
    clusterPoolIPv4PodCIDRList:
      - "192.168.64.0/20"
    clusterPoolIPv4MaskSize: 24
nodeIPAM:
  enabled: true
defaultLBServiceIPAM: "nodeipam"
hubble:
  enabled: true
  relay:
    enabled: true
  ui:
    enabled: true
