agents:
  argo-rollouts-agent:
    enabled: false
  istio-agent:
    enabled: false
  promql-agent:
    enabled: false
providers:
  default: ollama
  ollama:
    config:
      host: agentgateway-proxy.agentgateway-system.svc.cluster.local
      options:
        num_ctx: "32000"
    model: granite4.1:8b-q4_K_M
