apiVersion: agentgateway.dev/v1alpha1
kind: AgentgatewayBackend
metadata:
  name: google
  namespace: agentgateway-system
spec:
  ai:
    provider:
      gemini:
        model: gemini-3.1-flash-lite
  policies:
    auth:
      secretRef:
        name: agentgateway-google-secret
