apiVersion: ENC[AES256_GCM,data:9QA=,iv:BF1DctRVIvIMSJG1JqFYSuYQ4F+eCadCkQ0KRvAJh7o=,tag:IVcrD6+XHCViLlSz7IRygg==,type:str]
kind: ENC[AES256_GCM,data:ihDbK1Ku,iv:eoPkoU4e3TyRmeO4Yv9IxrfIoOj+4OcFUxmV2Z0MGWQ=,tag:pPMrN8nhdCvCaD+53+EDIQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:jIt6jD40ej7ri+fYgbIYax1ow3dogfic3WQ=,iv:Ci7+hBd9hIkqfE2X6ccDUvKgWnTXEUn0fhbxpROUL6E=,tag:+JTOMP0CS821DsKYqAmFTg==,type:str]
    namespace: ENC[AES256_GCM,data:KG++Ijh1aWE3N63xqkLtZmAXdw==,iv:/6OFmildlNYpVHCfJHmP/5XifBv+CNIvX9ZfiZNHKC4=,tag:JuKp5X7AoUdBocwmQ36VqA==,type:str]
type: ENC[AES256_GCM,data:ClsndrGm,iv:h68nTmpTZxz/nWFp4kuV0KpaKXmSDDwZCSo7PQNr/sQ=,tag:T4gU+nAYNR2FJzGJo43lqQ==,type:str]
stringData:
    Authorization: ENC[AES256_GCM,data:VSK4/vXlEoLY/p2PA5n44sqnYmVIZALol1spazS7sw008MUIYkF7,iv:yP5bcvpGO2Js2iM+tVBeJzJpK1HO1YWsaY8OZ6zEgIk=,tag:U+ZXJD6IkGKbm6V7CA/JaA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiYldEMEU1ZThFVU5RZnl4
            Wm5JR005clVlZzArWS9yZnptZWZwN3RuMEhVCk5xQm9wMklFcVg5KzZtRjdoVE1N
            WDl1OU9vQXhKc2huNnRkbC83UThzYWsKLS0tIHNUUUJFR3VXUjVFenl6N0JxdmpS
            UktWQ2tlWlJ3eXZqK3lReEwwWlVzN3MKOQ82n5haaUTst2enba3YNChFd0qD+nYu
            eLmnAsZjw735JdWnQ5V7hkI6fFAi/wLEaJ0OSF08Bag5IxXhYEYIIw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14hp778pa9t6yr58rn5ktprnaj7uah6p9ahuxrea4a4zfmscmsf3q97rdz3
    lastmodified: "2026-05-16T09:59:33Z"
    mac: ENC[AES256_GCM,data:RFQUsurvsnhG7ZyRypn0j7EtbAFLAbfFs0nLNyVI4rPgwodmROt8ITxT1zQWIL1CAcyVx7nhrGLDJncs66sorrykg+GXrx6gWjadZWz6TXrM10SpNNOURXXJwQrL/mGq8+q4yuNcG6uG0Rpx0i2ua49x+rLD702n2t0GFLbNGV8=,iv:tFKHpdcN1jbWpfqiDfgpRL/w68t47HLPrKpT2bU5XNg=,tag:8dJCPPaqqCX6avJ8OoNKow==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.0
