apiVersion: kagent.dev/v1alpha2
kind: ModelConfig
metadata:
  name: gemini
  namespace: kagent
spec:
  model: gemini-3.1-flash-lite
  provider: Ollama
  ollama:
    host: agentgateway-external.agentgateway-system.svc.cluster.local
