apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - agentgateway-backend-secrets.enc.yaml
  - agentgateway-backend.yaml
  - kagent.yaml
  - kagent-model.yaml
  - debug.yaml
